spring.application.name=disaster-relief

# 1. Database URL (3306 is the MySQL port, muhafiz_db is your database)
spring.datasource.url=jdbc:mysql://localhost:3306/muhafiz_db?useSSL=false&serverTimezone=UTC

# 2. Database Credentials
spring.datasource.username=root
spring.datasource.password=[your password]

# 3. Hibernate Configuration
# We set this to 'none' because you don't want to create tables yet.
# It will only check if the connection is successful.
spring.jpa.hibernate.ddl-auto=none


# 4. Driver and Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 5. Logging (To see if it connects)
spring.jpa.show-sql=true
